sudo: required

services:
  - docker

before_install:
   - sudo apt-get update
   - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
   - docker build -t hcscorp/bot .
   - docker push hcscorp/bot
